name: tekartik_barback
description: A pub package
dependencies:
  barback: any
dev_dependencies:
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
  process_run: any
  test: any
  dev_test: any

