name: tekartik_transformer
description: A pub package
dependencies:
  barback: any
#  tekartik_common:
#    path: ../../common
#  tekartik_io_tools:
#    git: git://github.com/alextekartik/tekartik_io_tools.dart
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
  process_run: any
#    git: git://github.com/tekartik/process_run.dart
dev_dependencies:
  test: any
  dev_test: any
# - tekartik_transformer/uppercase_transformer
  
