name: tekartik_in_uppercase_transformer
description: A pub package
dependencies:
  tekartik_barback:
    path: ../../..
dev_dependencies:
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
  test: any
  dev_test: any
transformers:
- tekartik_in_uppercase_transformer/uppercase_transformer
  
